### PR TITLE
Move shfmt to pre-commit

### PR DESCRIPTION
**Pull request by cbachhuber**
Try to resolve https://github.com/hofbi/telecarla/pull/33#discussion_r805385572

### CODE REVIEW

**Comment by hofbi** [comment]
According to their [README](https://github.com/scop/pre-commit-shfmt), they either require Go for the native setup or docker for the docker setup. With these dependencies neither solution is by default available

**Comment by cbachhuber** [comment]
Right, so I did a `sudo apt install golang` on my machine, but I get 

```
[INFO] Installing environment for https://github.com/scop/pre-commit-shfmt.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'config', 'remote.origin.url')
return code: 1
expected return code: 0
stdout:
    [Errno 2] No such file or directory: '/home/cbachhuber/.cache/pre-commit/repof6genny5': '/home/cbachhuber/.cache/pre-commit/repof6genny5'
    
stderr: (none)
Check the log at /home/cbachhuber/.cache/pre-commit/pre-commit.log
```

Same for you?

**Comment by hofbi** [comment]
The module requires go 1.16 for Ubuntu 20.04 go 1.13 is used in the apt packages. After installing go as on the go website, the check works.

However, I don't like that we need to install go just for having the shell formatter. Similar for the docker version since we should not make docker a dev dependency. I suggest that we look for another package.

**Comment by cbachhuber** [comment]
Agreed. I just tried https://github.com/syntaqx/git-hooks, that one doesn't work with pre-commit.ci :(

Seems like there's no straightforward way for including this. Close?

**Comment by hofbi** [comment]
Is there no possibility to install/include dependencies in the pre-commit ci?

**Comment by cbachhuber** [comment]
Doesn't look that way:

- I see [no corresponding arguments](https://pre-commit.ci/#configuration)
- It seems like pre-commit.ci is determined to keep their [runner image](https://github.com/pre-commit-ci/runner-image) as small as possible

Alternatively, we could move to the deprecated [pre-commit github action](https://github.com/pre-commit/action) and set up our own docker environment. Then, we can set up whatever we want.

**Comment by hofbi** [comment]
For now, let's leave it as is.

**Pull request closed without merging**
