### PR TITLE
Initial clang-tidy framework and fixes

### PR DESCRIPTION
**Pull request by cbachhuber**
There are checks I have still disabled and would like to discuss, see initial `.clang-tidy` file.

To be able to call clang-tidy, I first create a compilation database with

```shell
catkin_make -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```

then, still located in `catkin_ws`, I call

```shell
find src/telecarla/ -iname '*.cpp' | xargs clang-tidy -p build
```

Can we do this from the makefile? I guess we would need to go up two folders and back again. Additionally, it would be nice to check if the project has been built or at least configured (check if file `build/compile_commands.json` exists).

Do we want to run clang-tidy on test files? Currently, tests seem to pass clang-tidy, except for one weird ros include on my machine.

Finally: in `gstreaming_client.cpp` and `gstreaming_server.cpp`, our hand is forced to using char array, right? In that case, I suggest not linting that instance.

### CODE REVIEW

**Comment by hofbi** [comment]
We can enable all 3 options you mentioned in the `.clang-tidy` as TODO.

Yes we should do this in the Makefile. But I prefer to use the python catkin tools with `catkin build --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1` over `catkin_make ...`. It should be possible to call the catkin build command from every directory in the workspace so we are not forced to be in the workspace root. With this you can directly use the find function in the Makefile. Currently all functions in the Makefile use `.` as root dir. Optionally we could define the Makefile root with `ROOT_DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))` to be independent from the caller path. To get the path to the build folder, we could use `catkin locate --build` (see [docs](https://catkin-tools.readthedocs.io/en/latest/verbs/catkin_locate.html)). Can't we just run the catkin build command mentioned above every time as first command in the new make target. This should not contribute that much to the runtime if all packages are already built. So in summary, I would suggest to add a target to the Makefile for clang-tidy which calls `catkin build ...` and clang-tidy on all files. Also adding the clang-tidy target to the  `check` target to include this in the CI. It might be that we need to install clang-tidy in the CI.

Yes, we should also lint the tests. Maybe you can disable this one weird ros include.

Regarding the char array I guess we have to use it as `gst_init` expects argc and argv as usual. So we can disable this check here.

**Comment by cbachhuber** [comment]
There's one issue with `catkin build`: it keeps all builds nicely separated, leading to this layout in the build folder:

```shell
├── build
│   ├── catkin_tools_prebuild
│   │   ├── compile_commands.json
│   │   └── ...
│   ├── gstreaming
│   │   ├── compile_commands.json
│   │   └── ...
│   ├── telecarla
│   │   ├── compile_commands.json
│   │   └── ...
│   └── ...
```

In contrast to the build folder structure created by `catkin_make`

```shell
├── build
│   ├── compile_commands.json  # contains all compile commands
│   └── ...
```

`clang-tidy` can only consume one build folder with a `compile_commands.json`. I see these options to resolve:

1. Run clang-tidy [during build](https://moveit.ros.org/documentation/contributing/code/). I didn't get this to work yet, `catkin build` didn't execute clang-tidy. The commands should look something like
    ```shell
    catkin config --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_CLANG_TIDY=clang-tidy
    catkin build
    ```
1. Write a script to iterate over the folders inside `build`
1. Parse the `compile_commands.json` files in the subfolders of `build` as done [here](https://moveit.ros.org/documentation/contributing/code/)
1. Use catkin_make

Which method do you prefer? The first one seems to be the cleanest solution. If you agree, I would put more effort into that.

**Comment by hofbi** [comment]
Yes, 1 seems to be the best option here.

**Comment by cbachhuber** [comment]
With the current setup, we have clang-tidy running in CI as part of the ROS build.

- I think it's not good to have clang-tidy called from inside `Makefile`, as it requires a complete catkin workspace plus dependencies such as carla. The other `Makefile` checks don't.
- I first thought of duplicating the `ros` step from `ci.yml`, but I don't like the code and workload duplication caused by this.
- standard clang-tidy (version 6 on ubuntu 18.04) has some issues with the code in this repo, which is why I'm using clang-tidy-10

@hofbi, are you okay with the current way I'm invoking clang-tidy? If yes, I would proceed to uncomment and fix the remaining clang-tidy checks.

**Comment by hofbi** [comment]
Yes, sounds good. The check should be independent of the entire ROS part. Clang-tidy-10 is also fine. Maybe instead of manually installing it in the CI you could add it to the `install.sh`. This is already called in the CI runner setup.

**Comment by cbachhuber** [comment]
> The check should be independent of the entire ROS part.

What do you mean by this? That it should be conceptually independent, or that it should be a separate step?

**Comment by cbachhuber** [comment]
How about fixing the currently disabled clang-tidy checks in a follow-up PR, leaving them disabled for now? This PR is losing focus 😉

**Comment by hofbi** [comment]
The check should not contain any ROS related build steps to avoid the requirement of a configured workspace. So your decisions were all fine.

Agreed, lets fix them in the next PR.

**Pull request merged**
